### ISSUE TITLE
Design: Design QA 수정 작업

### ISSUE THREAD

**Issue by rai-95** [Prography-9th-3team/packit-web#42]
## 📝 이슈에 대한 설명

https://www.figma.com/design/zSDcaRxK6H4SxnE3KicPzj/Packit?node-id=415-13131&t=piBIZmabdXx1CQrd-1

## 📌 Task Lists

- [ ] : Avatar Button Case 추가
- [ ] : (버튼 공통) Loading Case 추가
- [ ] : (버튼 공통) Disabled case 추가
- [ ] : (버튼 공통) Icon case 추가
- [ ] : Select Arrow Icon 누락 수정
- [ ] : Focus 시 Hover 삭제
